language: c
sudo: required
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
env:
  - OCAML_VERSION=4.04 PACKAGE=ppx_iflet TESTS=false
  - OCAML_VERSION=4.03 PACKAGE=ppx_iflet TESTS=false
  - OCAML_VERSION=4.02 PACKAGE=ppx_iflet TESTS=false
